name: ci

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
          ref: 2bcc733ff64f887479de80f27818f93540c603e7

      - name: Build V
        run: |
          make
          sudo ./v symlink

      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          path: kpv

      - uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: "x64" # optional x64 or x86. Defaults to x64 if not specified

      - name: Format
        run: |
          cd ./kpv
          make format-check

      - name: Testing
        run: |
          cd ./kpv
          make test

      - name: Build kpv
        run: |
          cd ./kpv
          make linux

      - uses: actions/upload-artifact@v2
        with:
          name: linux
          path: ./kpv/bin/kpv_linux
          if-no-files-found: error

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
          ref: 2bcc733ff64f887479de80f27818f93540c603e7

      - name: Build V
        run: |
          .\make.bat -msvc

      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          path: kpv

      - uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: "x64" # optional x64 or x86. Defaults to x64 if not specified

      - name: Testing
        run: |
          $env:path += ";$(get-location)"
          cd ./kpv
          make test

      - name: Build kpv
        run: |
          $env:path += ";$(get-location)"
          cd ./kpv
          make windows

      - uses: actions/upload-artifact@v2
        with:
          name: windows
          path: ./kpv/bin/kpv_win.exe
          if-no-files-found: error

  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
          ref: 2bcc733ff64f887479de80f27818f93540c603e7

      - name: Build V
        run: |
          make
          sudo ./v symlink

      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          path: kpv

      - uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: "x64" # optional x64 or x86. Defaults to x64 if not specified

      - name: Testing
        run: |
          cd ./kpv
          make test

      - name: Build kpv
        run: |
          cd ./kpv
          make macos

      - uses: actions/upload-artifact@v2
        with:
          name: macos
          path: ./kpv/bin/kpv_osx
          if-no-files-found: error

  release:
    name: Release to Github
    if: startsWith(github.ref, 'refs/tags/') && github.repository == 'axetroy/kpv'
    needs: [linux, windows, macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: linux

      - uses: actions/download-artifact@v2
        with:
          name: windows

      - uses: actions/download-artifact@v2
        with:
          name: macos

      - name: tar
        run: |
          mv kpv_linux kpv && tar czf kpv_linux.tar.gz kpv && rm kpv
          mv kpv_osx kpv && tar czf kpv_osx.tar.gz kpv && rm kpv
          mv kpv_win.exe kpv.exe && tar czf kpv_win.tar.gz kpv.exe && rm kpv.exe
          ls -lh

      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          files: |
            kpv_linux.tar.gz
            kpv_osx.tar.gz
            kpv_win.tar.gz
          draft: false
